server:
  port: 38080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
          ignore-local-ssh-settings: true
          private-key:
          host-key:
          host-key-algorithm:
          timeout: 4
